export const SAMPLE = {

  mainCategories: [
    'Industrial Motherboards',
    'System-On-Modules',
    'Industrial Computers',
    'Application-Specific Systems',
    'Industrial Panel PCs & Displays',
    'Edge Servers',
    'Peripherals',
    'Software and Service',
  ],

  subCategories: {
    'Industrial Motherboards': [
      '1.8" SBC', '2.5" Pico-ITX', '3.5" SBC', '4" SBC',
      'PICMG 1.3', 'Mini-ITX', 'microATX', 'ATX', 'EATX',
    ],
    'System-On-Modules': [
      'COM Express Mini', 'COM Express Compact', 'COM Express Basic',
      'COM HPC', 'SMARC', 'Qseven', 'Open Standard Module (OSM)',
      'SDM', 'Carrier Boards',
    ],
    'Industrial Computers': [
      'Ultra Compact Fanless PC', 'Embedded Fanless PC',
      'Edge AI Inference Systems', 'Ruggedized Embedded Systems',
      'Mini-ITX / microATX / ATX Systems', 'IPC Chassis Series',
      'Performance Compact PC',
    ],
    'Application-Specific Systems': [
      'Railway Systems', 'In-vehicle Systems',
      'Medical Systems', 'Agile Gaming Systems',
    ],
    'Industrial Panel PCs & Displays': [
      'Fanless Touch Panel PC', 'Expandable Touch Panel PC',
      'Modularized Touch Panel PC', 'Open Frame Panel PC',
      'Industrial Display & Touch Display',
    ],
    'Edge Servers': [
      'Server Boards', 'Server System',
    ],
    'Peripherals': [
      'OOB Management', 'I/O Module', 'Riser Cards', 'Power Converters',
    ],
    'Software and Service': [
      'Ubuntu OS', 'OS Customization Service', 'ODM/OEM Service',
      'BIOS Customization Service', 'Software Customization Service',
      'Design Manufacturing Service', 'Reliable Technical Service', 'Extended Warranty',
    ],
  },

  filterCategoryMap: {
    '1.8" SBC':    ['Form Factor', 'CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    '2.5" Pico-ITX': ['Form Factor', 'CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    '3.5" SBC':    ['Form Factor', 'CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    '4" SBC':      ['Form Factor', 'CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    'PICMG 1.3':   ['CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    'Mini-ITX':    ['Form Factor', 'CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    'microATX':    ['CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    'ATX':         ['CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    'EATX':        ['CPU Platform', 'Memory Type', 'OS Support', 'Expansion', 'Operating Temp'],
    'COM Express Mini':           ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'COM Express Compact':        ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'COM Express Basic':          ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'COM HPC':                    ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'SMARC':                      ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'Qseven':                     ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'Open Standard Module (OSM)': ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'SDM':                        ['Module Standard', 'CPU Platform', 'Memory Type', 'Operating Temp'],
    'Carrier Boards':             ['CPU Platform', 'Expansion', 'Operating Temp'],
    'Ultra Compact Fanless PC':          ['CPU Platform', 'OS Support', 'LAN Ports', 'Expansion', 'Operating Temp'],
    'Embedded Fanless PC':               ['CPU Platform', 'OS Support', 'LAN Ports', 'Expansion', 'Operating Temp'],
    'Edge AI Inference Systems':         ['CPU Platform', 'OS Support', 'LAN Ports', 'Operating Temp'],
    'Ruggedized Embedded Systems':       ['CPU Platform', 'OS Support', 'Operating Temp'],
    'Mini-ITX / microATX / ATX Systems': ['CPU Platform', 'OS Support', 'LAN Ports', 'Expansion', 'Operating Temp'],
    'IPC Chassis Series':                ['Operating Temp'],
    'Performance Compact PC':            ['CPU Platform', 'OS Support', 'LAN Ports', 'Operating Temp'],
    'Railway Systems':      ['CPU Platform', 'Application Certification', 'Operating Temp'],
    'In-vehicle Systems':   ['CPU Platform', 'Application Certification', 'Operating Temp'],
    'Medical Systems':      ['CPU Platform', 'Application Certification', 'Operating Temp'],
    'Agile Gaming Systems': ['CPU Platform', 'OS Support', 'Operating Temp'],
    'Fanless Touch Panel PC':             ['CPU Platform', 'Screen Size', 'Touch Technology', 'IP Rating', 'OS Support', 'Operating Temp'],
    'Expandable Touch Panel PC':          ['CPU Platform', 'Screen Size', 'Touch Technology', 'IP Rating', 'OS Support', 'Operating Temp'],
    'Modularized Touch Panel PC':         ['CPU Platform', 'Screen Size', 'Touch Technology', 'IP Rating', 'OS Support', 'Operating Temp'],
    'Open Frame Panel PC':                ['CPU Platform', 'Screen Size', 'Touch Technology', 'IP Rating', 'OS Support', 'Operating Temp'],
    'Industrial Display & Touch Display': ['Screen Size', 'Touch Technology', 'IP Rating', 'Operating Temp'],
    'Server Boards': ['CPU Platform', 'Memory Type', 'Expansion', 'Operating Temp'],
    'Server System': ['CPU Platform', 'Memory Type', 'LAN Ports', 'Operating Temp'],
    'OOB Management':  ['Operating Temp'],
    'I/O Module':      ['Expansion', 'Operating Temp'],
    'Riser Cards':     ['Expansion', 'Operating Temp'],
    'Power Converters': ['Operating Temp'],
  },

  categories: [
    { name: 'Industrial Motherboards',          parent: null,                       sort: 1, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: '1.8" SBC',                         parent: 'Industrial Motherboards',  sort: 1, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:false } },
    { name: '2.5" Pico-ITX',                    parent: 'Industrial Motherboards',  sort: 2, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: '3.5" SBC',                         parent: 'Industrial Motherboards',  sort: 3, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: '4" SBC',                           parent: 'Industrial Motherboards',  sort: 4, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'PICMG 1.3',                        parent: 'Industrial Motherboards',  sort: 5, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Mini-ITX',                         parent: 'Industrial Motherboards',  sort: 6, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: 'microATX',                         parent: 'Industrial Motherboards',  sort: 7, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'ATX',                              parent: 'Industrial Motherboards',  sort: 8, langs: { EN:true,  TW:true,  CN:false, JP:false, DE:false } },
    { name: 'EATX',                             parent: 'Industrial Motherboards',  sort: 9, langs: { EN:true,  TW:false, CN:false, JP:false, DE:false } },
    { name: 'System-On-Modules',                parent: null,                       sort: 2, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: 'COM Express Mini',                 parent: 'System-On-Modules',        sort: 1, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:false } },
    { name: 'COM Express Compact',              parent: 'System-On-Modules',        sort: 2, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:false } },
    { name: 'COM Express Basic',                parent: 'System-On-Modules',        sort: 3, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'COM HPC',                          parent: 'System-On-Modules',        sort: 4, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'SMARC',                            parent: 'System-On-Modules',        sort: 5, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Qseven',                           parent: 'System-On-Modules',        sort: 6, langs: { EN:true,  TW:true,  CN:false, JP:false, DE:false } },
    { name: 'Open Standard Module (OSM)',       parent: 'System-On-Modules',        sort: 7, langs: { EN:true,  TW:false, CN:false, JP:false, DE:false } },
    { name: 'SDM',                              parent: 'System-On-Modules',        sort: 8, langs: { EN:true,  TW:false, CN:false, JP:false, DE:false } },
    { name: 'Carrier Boards',                   parent: 'System-On-Modules',        sort: 9, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Industrial Computers',             parent: null,                       sort: 3, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: 'Ultra Compact Fanless PC',         parent: 'Industrial Computers',     sort: 1, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:false } },
    { name: 'Embedded Fanless PC',              parent: 'Industrial Computers',     sort: 2, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: 'Edge AI Inference Systems',        parent: 'Industrial Computers',     sort: 3, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Ruggedized Embedded Systems',      parent: 'Industrial Computers',     sort: 4, langs: { EN:true,  TW:true,  CN:false, JP:false, DE:false } },
    { name: 'Mini-ITX / microATX / ATX Systems', parent: 'Industrial Computers',   sort: 5, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'IPC Chassis Series',               parent: 'Industrial Computers',     sort: 6, langs: { EN:true,  TW:true,  CN:false, JP:false, DE:false } },
    { name: 'Performance Compact PC',           parent: 'Industrial Computers',     sort: 7, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Application-Specific Systems',     parent: null,                       sort: 4, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: 'Railway Systems',                  parent: 'Application-Specific Systems', sort: 1, langs: { EN:true, TW:true, CN:true, JP:false, DE:true  } },
    { name: 'In-vehicle Systems',               parent: 'Application-Specific Systems', sort: 2, langs: { EN:true, TW:true, CN:true, JP:false, DE:false } },
    { name: 'Medical Systems',                  parent: 'Application-Specific Systems', sort: 3, langs: { EN:true, TW:true, CN:true, JP:false, DE:false } },
    { name: 'Agile Gaming Systems',             parent: 'Application-Specific Systems', sort: 4, langs: { EN:true, TW:false,CN:false,JP:false, DE:false } },
    { name: 'Industrial Panel PCs & Displays',  parent: null,                       sort: 5, langs: { EN:true,  TW:true,  CN:true,  JP:true,  DE:true  } },
    { name: 'Fanless Touch Panel PC',           parent: 'Industrial Panel PCs & Displays', sort: 1, langs: { EN:true, TW:true, CN:true, JP:true,  DE:false } },
    { name: 'Expandable Touch Panel PC',        parent: 'Industrial Panel PCs & Displays', sort: 2, langs: { EN:true, TW:true, CN:true, JP:false, DE:false } },
    { name: 'Modularized Touch Panel PC',       parent: 'Industrial Panel PCs & Displays', sort: 3, langs: { EN:true, TW:true, CN:false,JP:false, DE:false } },
    { name: 'Open Frame Panel PC',              parent: 'Industrial Panel PCs & Displays', sort: 4, langs: { EN:true, TW:true, CN:true, JP:false, DE:false } },
    { name: 'Industrial Display & Touch Display', parent: 'Industrial Panel PCs & Displays', sort: 5, langs: { EN:true, TW:true, CN:false,JP:false, DE:false } },
    { name: 'Edge Servers',                     parent: null,                       sort: 6, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Server Boards',                    parent: 'Edge Servers',             sort: 1, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Server System',                    parent: 'Edge Servers',             sort: 2, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'Peripherals',                      parent: null,                       sort: 7, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
    { name: 'OOB Management',                   parent: 'Peripherals',              sort: 1, langs: { EN:true,  TW:true,  CN:false, JP:false, DE:false } },
    { name: 'I/O Module',                       parent: 'Peripherals',              sort: 2, langs: { EN:true,  TW:true,  CN:false, JP:false, DE:false } },
    { name: 'Riser Cards',                      parent: 'Peripherals',              sort: 3, langs: { EN:true,  TW:false, CN:false, JP:false, DE:false } },
    { name: 'Power Converters',                 parent: 'Peripherals',              sort: 4, langs: { EN:true,  TW:false, CN:false, JP:false, DE:false } },
    { name: 'Software and Service',             parent: null,                       sort: 8, langs: { EN:true,  TW:true,  CN:true,  JP:false, DE:false } },
  ],

  filters: [
    {
      name: 'Form Factor',
      options: ['1.8" SBC', '2.5" Pico-ITX', '3.5" SBC', '4" SBC', 'Mini-ITX', 'microATX', 'ATX', 'EATX', 'PICMG 1.3'],
      sort: 1, status: 'active', langs: { EN:true, TW:true, CN:true, JP:true, DE:true },
    },
    {
      name: 'CPU Platform',
      options: [
        'Intel Core Ultra Series 2 (Arrow Lake)',
        'Intel Core Ultra Series 1 (Meteor Lake)',
        'Intel 14th Gen Core (Raptor Lake-R)',
        'Intel 12th/13th Gen Core (Alder/Raptor Lake)',
        'Intel Atom x6000E (Elkhart Lake)',
        'Intel Celeron J6412 (Elkhart Lake)',
        'AMD Ryzen Embedded V3000',
        'NXP i.MX8M Plus',
      ],
      sort: 2, status: 'active', langs: { EN:true, TW:true, CN:true, JP:true, DE:true },
    },
    {
      name: 'Operating Temp',
      options: ['0~60°C (Standard)', '-20~60°C (Extended)', '-40~85°C (Wide)'],
      sort: 3, status: 'active', langs: { EN:true, TW:true, CN:true, JP:true, DE:true },
    },
    {
      name: 'OS Support',
      options: [
        'Windows 11 IoT Enterprise',
        'Windows 10 IoT Enterprise',
        'Linux Ubuntu 22.04 LTS',
        'Linux Ubuntu 20.04 LTS',
        'Android 13',
        'VxWorks',
        'QNX',
      ],
      sort: 4, status: 'active', langs: { EN:true, TW:true, CN:true, JP:false, DE:false },
    },
    {
      name: 'Memory Type',
      options: ['DDR5', 'DDR4', 'LPDDR5', 'LPDDR4x'],
      sort: 5, status: 'active', langs: { EN:true, TW:true, CN:true, JP:false, DE:false },
    },
    {
      name: 'Expansion',
      options: ['PCIe x16', 'PCIe x4', 'PCIe x1', 'M.2 2280 (NVMe)', 'M.2 2242', 'mPCIe', 'SATA III'],
      sort: 6, status: 'active', langs: { EN:true, TW:true, CN:false, JP:false, DE:false },
    },
    {
      name: 'LAN Ports',
      options: ['2x GbE', '4x GbE', '6x GbE', '1x 2.5GbE + 1x GbE', '2x 10GbE', '4x 10GbE'],
      sort: 7, status: 'active', langs: { EN:true, TW:true, CN:true, JP:false, DE:false },
    },
    {
      name: 'Module Standard',
      options: [
        'COM Express Rev. 3.1 (Mini)', 'COM Express Rev. 3.1 (Compact)', 'COM Express Rev. 3.1 (Basic)',
        'COM HPC Rev. 1.0', 'SMARC 2.1', 'Qseven R2.1', 'OSM Rev. 1.0',
      ],
      sort: 8, status: 'active', langs: { EN:true, TW:true, CN:false, JP:false, DE:false },
    },
    {
      name: 'Application Certification',
      options: ['EN 50155 (Railway)', 'EN 50121-3-2 (EMC Railway)', 'MIL-STD-810G (Military)', 'IEC 60601-1 (Medical)', 'ISO 13849 (Safety)'],
      sort: 9, status: 'active', langs: { EN:true, TW:true, CN:false, JP:false, DE:false },
    },
    {
      name: 'Screen Size',
      options: ['7"', '10.1"', '12.1"', '15.6"', '17.3"', '21.5"', '23.8"'],
      sort: 10, status: 'active', langs: { EN:true, TW:true, CN:true, JP:false, DE:false },
    },
    {
      name: 'Touch Technology',
      options: ['Projected Capacitive (PCAP)', 'Resistive', 'SAW (Surface Acoustic Wave)'],
      sort: 11, status: 'active', langs: { EN:true, TW:true, CN:false, JP:false, DE:false },
    },
    {
      name: 'IP Rating',
      options: ['IP54', 'IP65', 'IP66', 'IP67'],
      sort: 12, status: 'active', langs: { EN:true, TW:true, CN:false, JP:false, DE:false },
    },
  ],

  tags: [
    { name: 'AI Edge',               slug: 'ai-edge',               langs: { EN:true, TW:true, CN:true,  JP:true,  DE:true  } },
    { name: 'IoT Gateway',           slug: 'iot-gateway',           langs: { EN:true, TW:true, CN:true,  JP:false, DE:false } },
    { name: 'In-Vehicle',            slug: 'in-vehicle',            langs: { EN:true, TW:true, CN:false, JP:false, DE:false } },
    { name: 'Industrial Automation', slug: 'industrial-automation', langs: { EN:true, TW:true, CN:true,  JP:true,  DE:false } },
    { name: 'Smart Retail',          slug: 'smart-retail',          langs: { EN:true, TW:false,CN:false, JP:false, DE:false } },
  ],

  specGroups: [
    { name: 'General',            category: 'Industrial Motherboards', sort: 1, fields: 5 },
    { name: 'I/O Interface',      category: 'Industrial Motherboards', sort: 2, fields: 6 },
    { name: 'Power & Mechanical', category: 'Industrial Computers',    sort: 1, fields: 4 },
    { name: 'Expansion',          category: 'Industrial Computers',    sort: 2, fields: 3 },
  ],

  products: [
    { model: 'EC70A-SU', mainCat: 'Industrial Motherboards', subCat: '3.5" SBC', lifecycle: 'Active', status: '待更新', updated: '2026-04-10 14:32',
      langStatuses: [
        { code: 'en', name: 'EN', enabled: true,  status: 'needs_update', lastSynced: '2026-04-10' },
        { code: 'tw', name: 'TW', enabled: true,  status: 'pending',      lastSynced: '2026-04-08' },
        { code: 'cn', name: 'CN', enabled: true,  status: 'synced',       lastSynced: '2026-04-08' },
        { code: 'jp', name: 'JP', enabled: true,  status: 'sync_failed',  lastSynced: '2026-04-05' },
        { code: 'de', name: 'DE', enabled: false, status: null,           lastSynced: null },
      ]},
    { model: 'EC551-CR', mainCat: 'Industrial Motherboards', subCat: '3.5" SBC', lifecycle: 'Active', status: '已發佈', updated: '2026-04-08 09:17',
      langStatuses: [
        { code: 'en', name: 'EN', enabled: true,  status: 'synced', lastSynced: '2026-04-08' },
        { code: 'tw', name: 'TW', enabled: true,  status: 'synced', lastSynced: '2026-04-08' },
        { code: 'cn', name: 'CN', enabled: true,  status: 'synced', lastSynced: '2026-04-08' },
        { code: 'jp', name: 'JP', enabled: false, status: null,     lastSynced: null },
        { code: 'de', name: 'DE', enabled: false, status: null,     lastSynced: null },
      ]},
    { model: 'SD101-D26', mainCat: 'Industrial Computers', subCat: 'Embedded Fanless PC', lifecycle: 'Active', status: '待發佈', updated: '2026-03-25 16:44',
      langStatuses: [
        { code: 'en', name: 'EN', enabled: true,  status: 'pending', lastSynced: null },
        { code: 'tw', name: 'TW', enabled: true,  status: 'draft',   lastSynced: null },
        { code: 'cn', name: 'CN', enabled: false, status: null,      lastSynced: null },
        { code: 'jp', name: 'JP', enabled: false, status: null,      lastSynced: null },
        { code: 'de', name: 'DE', enabled: false, status: null,      lastSynced: null },
      ]},
    { model: 'IPC900-519-FL', mainCat: 'Industrial Computers', subCat: 'Embedded Fanless PC', lifecycle: 'Active', status: '待發佈', updated: '2026-03-18 11:20',
      langStatuses: [
        { code: 'en', name: 'EN', enabled: true,  status: 'pending', lastSynced: null },
        { code: 'tw', name: 'TW', enabled: false, status: null,      lastSynced: null },
        { code: 'cn', name: 'CN', enabled: false, status: null,      lastSynced: null },
        { code: 'jp', name: 'JP', enabled: false, status: null,      lastSynced: null },
        { code: 'de', name: 'DE', enabled: false, status: null,      lastSynced: null },
      ]},
    { model: 'VC972-R10', mainCat: 'Application-Specific Systems', subCat: 'In-vehicle Systems', lifecycle: 'EOL', status: '已發佈', updated: '2025-12-01 08:05',
      langStatuses: [
        { code: 'en', name: 'EN', enabled: true, status: 'synced', lastSynced: '2025-12-01' },
        { code: 'tw', name: 'TW', enabled: true, status: 'synced', lastSynced: '2025-12-01' },
        { code: 'cn', name: 'CN', enabled: true, status: 'synced', lastSynced: '2025-12-01' },
        { code: 'jp', name: 'JP', enabled: true, status: 'synced', lastSynced: '2025-12-01' },
        { code: 'de', name: 'DE', enabled: true, status: 'synced', lastSynced: '2025-12-01' },
      ]},
    { model: 'EC70A-BT', mainCat: 'Industrial Motherboards', subCat: '3.5" SBC', lifecycle: 'Preview', status: '草稿', updated: '2026-04-14 17:00',
      langStatuses: [
        { code: 'en', name: 'EN', enabled: true,  status: 'draft', lastSynced: null },
        { code: 'tw', name: 'TW', enabled: false, status: null,    lastSynced: null },
        { code: 'cn', name: 'CN', enabled: false, status: null,    lastSynced: null },
        { code: 'jp', name: 'JP', enabled: false, status: null,    lastSynced: null },
        { code: 'de', name: 'DE', enabled: false, status: null,    lastSynced: null },
      ]},
  ],

  productEdit: {
    model:    'EC70A-SU',
    lifecycle: 'Active',
    primaryParent: 'Industrial Motherboards',
    primarySub:    '3.5" SBC',
    secondaryCats: ['Industrial Computers', 'Edge AI Inference Systems'],
    filters:  ['Form Factor: 3.5" SBC', 'CPU Platform: Intel 12th/13th Gen Core (Alder/Raptor Lake)', 'OS Support: Windows 10 IoT Enterprise', 'Operating Temp: -20~60°C (Extended)'],
    tags:     ['AI Edge', 'Industrial Automation'],
    langStatuses: [
      { code: 'en', name: 'EN', status: 'pending',     lastSynced: '2026-04-10' },
      { code: 'tw', name: 'TW', status: 'draft',       lastSynced: null },
      { code: 'cn', name: 'CN', status: 'synced',      lastSynced: '2026-04-08' },
      { code: 'jp', name: 'JP', status: 'sync_failed', lastSynced: '2026-04-05', syncError: 'API timeout (503)' },
      { code: 'de', name: 'DE', status: 'draft',       lastSynced: null, disabled: true },
    ],
    specs: [
      { group: 'General', fields: [
        { label: 'CPU',        value: 'Intel® Core™ i7-1185G7E, 4C/8T, up to 4.4GHz (Tiger Lake-UP4)' },
        { label: 'Chipset',    value: 'Intel® Tiger Lake-UP4 Platform' },
        { label: 'Memory',     value: 'DDR4-3200, 2x SODIMM, up to 64GB' },
        { label: 'Storage',    value: '1x M.2 2280 PCIe Gen 3 x4 (NVMe), 1x SATA III 6Gb/s' },
        { label: 'OS Support', value: 'Windows 10/11 IoT Enterprise, Linux Ubuntu 20.04 LTS' },
      ]},
      { group: 'I/O Interface', fields: [
        { label: 'LAN',     value: '2x Intel GbE (i219LM + i210AT), supports WoL' },
        { label: 'USB',     value: '4x USB 3.2 Gen 1 (5Gbps), 2x USB 2.0' },
        { label: 'Display', value: '1x HDMI 2.0 (4K@60Hz), 1x DisplayPort 1.4 (4K@60Hz)' },
        { label: 'Serial',  value: '2x RS-232/422/485 (software selectable, isolated)' },
        { label: 'Audio',   value: '1x Line-out, 1x Mic-in (Realtek ALC662)' },
        { label: 'GPIO',    value: '8-bit Digital I/O (4-in / 4-out)' },
      ]},
      { group: 'Power & Mechanical', fields: [
        { label: 'Power Input',    value: 'DC-in 12V/24V (9~36V), 60W max' },
        { label: 'Operating Temp', value: '-20°C to 60°C (with extended temp CPU)' },
        { label: 'Dimension',      value: '146 x 101 mm (3.5" SBC form factor)' },
        { label: 'Weight',         value: '~400g (board only)' },
      ]},
    ],
    ordering: {
      dynamicCols: [
        { key: 'lan', label: 'LAN Port' },
        { key: 'usb', label: 'USB Port' },
      ],
      visibleColKeys: ['modelName', 'pn', 'processor', 'memory', 'thermal', 'operatingTemp', 'lan', 'usb'],
      rows: [
        { modelName: 'EC70A-SU', pn: 'EC70A-SU-0001', processor: 'Intel® Core™ i7-1185G7E', memory: 'DDR4, up to 64GB', thermal: 'Fanless', operatingTemp: '-20°C ~ 60°C', lan: 2, usb: 6 },
        { modelName: 'EC70A-SU', pn: 'EC70A-SU-0002', processor: 'Intel® Core™ i5-1145G7E', memory: 'DDR4, up to 32GB', thermal: 'Fanless', operatingTemp: '-20°C ~ 60°C', lan: 2, usb: 6 },
        { modelName: 'EC70A-SU', pn: 'EC70A-SU-0003', processor: 'Intel® Core™ i3-1115G4E', memory: 'DDR4, up to 16GB', thermal: 'Fanless', operatingTemp: '-20°C ~ 60°C', lan: 2, usb: 4 },
      ],
    },
    skuSpecs: {
      skus: [
        { pn: 'EC70A-SU-0001', desc: 'Core i7-1185G7E' },
        { pn: 'EC70A-SU-0002', desc: 'Core i5-1145G7E' },
        { pn: 'EC70A-SU-0003', desc: 'Core i3-1115G4E' },
      ],
      groups: [
        { group: 'General', fields: [
          { label: 'CPU',        values: ['Intel® Core™ i7-1185G7E, 4C/8T, 4.4GHz', 'Intel® Core™ i5-1145G7E, 4C/8T, 4.1GHz', 'Intel® Core™ i3-1115G4E, 2C/4T, 3.9GHz'] },
          { label: 'Chipset',    values: ['Intel® Tiger Lake-UP4', 'Intel® Tiger Lake-UP4', 'Intel® Tiger Lake-UP4'] },
          { label: 'Memory',     values: ['DDR4-3200, up to 64GB', 'DDR4-3200, up to 32GB', 'DDR4-3200, up to 16GB'] },
          { label: 'Storage',    values: ['M.2 PCIe x4 + SATA III', 'M.2 PCIe x4 + SATA III', 'M.2 PCIe x4 + SATA III'] },
          { label: 'OS Support', values: ['Win 10/11 IoT, Ubuntu 20.04', 'Win 10/11 IoT, Ubuntu 20.04', 'Win 10/11 IoT, Ubuntu 20.04'] },
        ]},
        { group: 'I/O Interface', fields: [
          { label: 'LAN',     values: ['2x Intel GbE', '2x Intel GbE', '2x Intel GbE'] },
          { label: 'USB',     values: ['4x USB 3.2 + 2x USB 2.0', '4x USB 3.2 + 2x USB 2.0', '4x USB 3.2 + 2x USB 2.0'] },
          { label: 'Display', values: ['HDMI 2.0 + DP 1.4', 'HDMI 2.0 + DP 1.4', 'HDMI 2.0 + DP 1.4'] },
          { label: 'Serial',  values: ['2x RS-232/422/485', '2x RS-232/422/485', '2x RS-232/422/485'] },
          { label: 'Audio',   values: ['Line-out + Mic-in', 'Line-out + Mic-in', 'Line-out + Mic-in'] },
          { label: 'GPIO',    values: ['8-bit DIO', '8-bit DIO', '8-bit DIO'] },
        ]},
        { group: 'Power & Mechanical', fields: [
          { label: 'Power Input',    values: ['DC 9~36V, 60W', 'DC 9~36V, 60W', 'DC 9~36V, 60W'] },
          { label: 'Operating Temp', values: ['-20°C ~ 60°C', '-20°C ~ 60°C', '-20°C ~ 60°C'] },
          { label: 'Dimension',      values: ['146 x 101 mm', '146 x 101 mm', '146 x 101 mm'] },
          { label: 'Weight',         values: ['~400g', '~400g', '~400g'] },
        ]},
      ]
    },
    landings: {
      en: {
        features: 'Powered by Intel® 11th Gen Core™ Tiger Lake-E — exceptional performance\nWide-temp operation -20°C ~ 60°C for harsh industrial environments\nDual GbE (Intel i219LM + i210AT) with TSN support\nRich I/O: RS-232/422/485 x2, USB 3.2 x4, 8-bit GPIO\nSupports Windows 10/11 IoT Enterprise and Linux Ubuntu',
        seoTitle: 'EC70A-SU 3.5" SBC | Intel 11th Gen Tiger Lake-E | DFI',
        seoKeywords: 'EC70A-SU, 3.5 SBC, embedded computing, Tiger Lake-E, industrial SBC',
        seoDesc: 'The DFI EC70A-SU is a 3.5" SBC powered by Intel 11th Gen Core i7/i5/i3 Tiger Lake-E, featuring wide-temp support and rich I/O for industrial automation and AIoT applications.',
      },
      tw: {
        features: '搭載 Intel® 第 11 代 Core™ Tiger Lake-E 處理器，效能強勁\n寬溫運行 -20°C ~ 60°C，適應嚴苛工業環境\n雙 GbE 網路（Intel i219LM + i210AT），支援 TSN\n豐富 I/O：RS-232/422/485 x2、USB 3.2 x4、8-bit GPIO\n支援 Windows 10/11 IoT Enterprise 及 Linux Ubuntu',
        seoTitle: 'EC70A-SU 3.5" SBC | Intel 第 11 代 Tiger Lake-E | DFI',
        seoKeywords: 'EC70A-SU, 3.5 SBC, 嵌入式電腦, Tiger Lake-E, 工業用單板電腦',
        seoDesc: 'DFI EC70A-SU 是搭載 Intel 第 11 代 Core i7/i5/i3 Tiger Lake-E 的 3.5" 單板電腦，提供寬溫支援與豐富 I/O，適用於工業自動化與 AIoT 應用。',
      },
      cn: {
        features: '搭载 Intel® 第 11 代 Core™ Tiger Lake-E 处理器，性能卓越\n宽温运行 -20°C ~ 60°C，适应严苛工业环境\n双 GbE 网络（Intel i219LM + i210AT），支持 TSN\n丰富 I/O：RS-232/422/485 x2、USB 3.2 x4、8-bit GPIO\n支持 Windows 10/11 IoT Enterprise 及 Linux Ubuntu',
        seoTitle: 'EC70A-SU 3.5" SBC | 英特尔第 11 代 Tiger Lake-E | DFI',
        seoKeywords: 'EC70A-SU, 3.5 SBC, 嵌入式计算, Tiger Lake-E, 工业单板电脑',
        seoDesc: 'DFI EC70A-SU 是搭载英特尔第 11 代 Core i7/i5/i3 Tiger Lake-E 的 3.5" 单板电脑，提供宽温支持与丰富 I/O，适用于工业自动化与 AIoT 应用。',
      },
      jp: { features: '', seoTitle: '', seoKeywords: '', seoDesc: '' },
      de: { features: '', seoTitle: '', seoKeywords: '', seoDesc: '' },
    },
    relations: {
      derivatives: ['EC70A-BT'],
      accessories: ['EC551-CR'],
    },
  },

  categoryEdit: {
    type: 'sub',
    parentId: 'Industrial Motherboards',
    sort: 3,
    langStatuses: [
      { code: 'en', name: 'EN', status: 'synced',   lastSynced: '2026-04-10' },
      { code: 'tw', name: 'TW', status: 'draft',    lastSynced: null },
      { code: 'cn', name: 'CN', status: 'synced',   lastSynced: '2026-04-08' },
      { code: 'jp', name: 'JP', status: 'draft',    lastSynced: null },
      { code: 'de', name: 'DE', status: 'draft',    lastSynced: null, disabled: true },
    ],
    landings: {
      en: { name: '3.5" SBC', desc: 'Compact 3.5" single board computers for industrial and embedded applications.', image: null, seoSlug: '3-5-sbc', seoTitle: '3.5" SBC | Industrial Single Board Computers | DFI', seoDesc: 'Browse DFI\'s 3.5" SBC series — ruggedized single board computers for industrial automation, AIoT, and embedded computing applications.' },
      tw: { name: '3.5" 單板電腦', desc: '適用於工業與嵌入式應用的緊湊型 3.5" 單板電腦。', image: null, seoSlug: '3-5-sbc', seoTitle: '3.5" 單板電腦 | 工業用單板電腦 | DFI', seoDesc: '瀏覽 DFI 3.5" SBC 系列 — 專為工業自動化、AIoT 及嵌入式運算應用設計的耐用型單板電腦。' },
      cn: { name: '3.5" 单板电脑', desc: '适用于工业与嵌入式应用的紧凑型 3.5" 单板电脑。', image: null, seoSlug: '3-5-sbc', seoTitle: '3.5" 单板电脑 | 工业单板电脑 | DFI', seoDesc: '浏览 DFI 3.5" SBC 系列 — 专为工业自动化、AIoT 及嵌入式计算应用设计的耐用型单板电脑。' },
      jp: { name: '3.5" SBC', desc: '産業用および組み込みアプリケーション向けのコンパクトな 3.5" シングルボードコンピュータ。', image: null, seoSlug: '3-5-sbc', seoTitle: '3.5" SBC | 産業用シングルボードコンピュータ | DFI', seoDesc: '' },
      de: { name: '3,5" SBC', desc: 'Kompakte 3,5"-Einplatinencomputer für industrielle und eingebettete Anwendungen.', image: null, seoSlug: '3-5-sbc', seoTitle: '3,5" SBC | Industrie-Einplatinencomputer | DFI', seoDesc: '' },
    },
    featuredProducts: ['EC70A-SU', 'EC551-CR'],
  },

  files: [
    { name: 'EC70A-SU Datasheet v1.2',            mainCategory: '文件資料', subCategory: 'Datasheet',         type: 'PDF', status: '啟用', updated: '2026-04-01' },
    { name: 'EC551-CR Quick Start Guide',          mainCategory: '文件資料', subCategory: 'Quick Start Guide', type: 'PDF', status: '啟用', updated: '2026-03-15' },
    { name: 'IPC900-519-FL User Manual',           mainCategory: '文件資料', subCategory: 'User Manual',       type: 'PDF', status: '停用', updated: '2026-02-20' },
    { name: 'EC70A-SU BIOS v1.3.2',               mainCategory: '軟體驅動', subCategory: 'BIOS / Driver',     type: 'ZIP', status: '啟用', updated: '2026-04-12' },
    { name: 'DFI Embedded Product Catalog Q2 2026', mainCategory: '行銷素材', subCategory: 'Brochure',        type: 'PDF', status: '啟用', updated: '2026-03-01' },
  ],

  fileCategories: [
    { name: 'Datasheet',         parent: '—' },
    { name: 'Quick Start Guide', parent: '—' },
    { name: 'User Manual',       parent: '—' },
    { name: 'BIOS / Driver',     parent: '—' },
    { name: 'Brochure',          parent: '—' },
  ],

  users: [
    { name: 'System Admin', email: 'admin@dfi.com',       company: 'DFI', dept: 'IT',                 role: 'Admin',    status: 'active'   },
    { name: 'Alan Chen',    email: 'alan.chen@dfi.com',   company: 'DFI', dept: 'Product Management', role: 'PM',       status: 'active'   },
    { name: 'Lisa Wang',    email: 'lisa.wang@dfi.com',   company: 'DFI', dept: 'Marketing',          role: 'MKT',      status: 'active'   },
    { name: 'Kevin Lee',    email: 'kevin.lee@dfi.com',   company: 'DFI', dept: 'Design',             role: 'Designer', status: 'active'   },
    { name: 'Tina Huang',   email: 'tina.huang@dfi.com',  company: 'DFI', dept: 'FAE',                role: 'FAE',      status: 'active'   },
    { name: 'Mark Lin',     email: 'mark.lin@dfi.com',    company: 'DFI', dept: 'Sales',              role: 'MKT',      status: 'inactive' },
  ],

  roles: [
    { name: 'Admin',    desc: '系統管理員，擁有全部功能的讀寫權限',          status: 'active' },
    { name: 'PM',       desc: '產品經理，可管理產品資訊、規格與分類',         status: 'active' },
    { name: 'MKT',      desc: '行銷人員，可管理 Landing Page 與 SEO 內容',  status: 'active' },
    { name: 'Designer', desc: '設計師，可上傳與管理產品圖片及視覺資源',       status: 'active' },
    { name: 'FAE',      desc: '技術支援工程師，可管理下載檔案',              status: 'active' },
  ],

  auditLogs: [
    { user: 'Alan Chen',    module: '產品管理', page: '產品編輯',   action: 'UPDATE', target: 'EC70A-SU',             time: '2026-04-15 10:23' },
    { user: 'Lisa Wang',    module: '產品管理', page: '產品編輯',   action: 'UPDATE', target: 'EC70A-SU',             time: '2026-04-14 17:05' },
    { user: 'Kevin Lee',    module: '產品管理', page: '產品編輯',   action: 'UPDATE', target: 'EC551-CR',             time: '2026-04-14 15:40' },
    { user: 'Tina Huang',   module: '檔案管理', page: '檔案列表',   action: 'CREATE', target: 'EC70A-SU BIOS v1.3.2', time: '2026-04-12 11:18' },
    { user: 'Alan Chen',    module: '產品管理', page: '產品列表',   action: 'CREATE', target: 'EC70A-BT',             time: '2026-04-10 09:32' },
    { user: 'System Admin', module: '帳號管理', page: '使用者管理', action: 'UPDATE', target: 'Tina Huang',           time: '2026-04-08 14:50' },
  ],

  errorLogs: [
    { user: 'System',       module: '產品管理', source: 'Sync Job',    target: 'EC551-CR',            type: 'API 錯誤', msg: 'Failed to sync: upstream timeout (dfi.com /api/products)', time: '2026-04-15 06:01' },
    { user: 'Lisa Wang',    module: '產品管理', source: '產品編輯',    target: 'SD101-D26',           type: '驗證失敗', msg: '必填欄位缺失：Short Description（EN）',                    time: '2026-04-13 15:22' },
    { user: 'Kevin Lee',    module: '檔案管理', source: '檔案列表',    target: 'product-image.jpg',   type: '系統錯誤', msg: 'File upload failed: max size exceeded (52 MB > 50 MB)',    time: '2026-04-12 10:55' },
    { user: 'System',       module: '產品管理', source: 'Sync Job',    target: 'SD101-D26',           type: 'API 錯誤', msg: '官網 API timeout，retry 3 次後放棄',                       time: '2026-04-10 06:00' },
    { user: 'System Admin', module: '帳號管理', source: '使用者管理',  target: 'clin@dfi.com',        type: '驗證失敗', msg: '密碼格式不符規則，登入失敗',                               time: '2026-04-08 09:10' },
  ],
};
